/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#00458d",
        "tertiary-fixed-dim": "#eac32b",
        "outline": "#8c919d",
        "on-surface-variant": "#c2c6d4",
        "secondary": "#aac7ff",
        "on-tertiary-container": "#4d3e00",
        "surface-container-lowest": "#000e26",
        "on-primary-fixed-variant": "#564500",
        "on-tertiary": "#3b2f00",
        "inverse-primary": "#725c00",
        "tertiary": "#eac32b",
        "on-primary": "#3c2f00",
        "inverse-on-surface": "#022f63",
        "surface": "#00132f",
        "primary-container": "#745e00",
        "on-tertiary-fixed": "#231b00",
        "on-primary-fixed": "#231b00",
        "on-surface": "#d6e3ff",
        "on-primary-container": "#ffd853",
        "on-tertiary-fixed-variant": "#564500",
        "on-error": "#690005",
        "inverse-surface": "#d6e3ff",
        "surface-dim": "#00132f",
        "secondary-fixed-dim": "#aac7ff",
        "outline-variant": "#424752",
        "secondary-container": "#0053a7",
        "surface-variant": "#0a3468",
        "primary": "#eec200",
        "surface-container-high": "#002959",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-background": "#d6e3ff",
        "on-secondary-container": "#afcaff",
        "on-secondary-fixed": "#001b3e",
        "on-secondary": "#002f64",
        "background": "#00132f",
        "secondary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#eec200",
        "surface-bright": "#12396d",
        "surface-container-low": "#001b3e",
        "primary-fixed": "#ffe081",
        "tertiary-container": "#cca800",
        "tertiary-fixed": "#ffe17b",
        "surface-container": "#001f46",
        "surface-container-highest": "#0a3468",
        "surface-tint": "#eec200",
        "error-container": "#93000a"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
